package org.goodsManagement.po;

public class GetGoodsDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column getgoods.id
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column getgoods.staffid
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    private Integer staffid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column getgoods.goodid
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    private Integer goodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column getgoods.getnumber
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    private Integer getnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column getgoods.id
     *
     * @return the value of getgoods.id
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column getgoods.id
     *
     * @param id the value for getgoods.id
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column getgoods.staffid
     *
     * @return the value of getgoods.staffid
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    public Integer getStaffid() {
        return staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column getgoods.staffid
     *
     * @param staffid the value for getgoods.staffid
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    public void setStaffid(Integer staffid) {
        this.staffid = staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column getgoods.goodid
     *
     * @return the value of getgoods.goodid
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column getgoods.goodid
     *
     * @param goodid the value for getgoods.goodid
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column getgoods.getnumber
     *
     * @return the value of getgoods.getnumber
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    public Integer getGetnumber() {
        return getnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column getgoods.getnumber
     *
     * @param getnumber the value for getgoods.getnumber
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    public void setGetnumber(Integer getnumber) {
        this.getnumber = getnumber;
    }
}