package org.goodsManagement.po;

public class GoodsDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodname
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private String goodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodunit
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private String goodunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodnumbers
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Integer goodnumbers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodtype
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private String goodtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodname
     *
     * @return the value of goods.goodname
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public String getGoodname() {
        return goodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodname
     *
     * @param goodname the value for goods.goodname
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setGoodname(String goodname) {
        this.goodname = goodname == null ? null : goodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodunit
     *
     * @return the value of goods.goodunit
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public String getGoodunit() {
        return goodunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodunit
     *
     * @param goodunit the value for goods.goodunit
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setGoodunit(String goodunit) {
        this.goodunit = goodunit == null ? null : goodunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodnumbers
     *
     * @return the value of goods.goodnumbers
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Integer getGoodnumbers() {
        return goodnumbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodnumbers
     *
     * @param goodnumbers the value for goods.goodnumbers
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setGoodnumbers(Integer goodnumbers) {
        this.goodnumbers = goodnumbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodtype
     *
     * @return the value of goods.goodtype
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public String getGoodtype() {
        return goodtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodtype
     *
     * @param goodtype the value for goods.goodtype
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setGoodtype(String goodtype) {
        this.goodtype = goodtype == null ? null : goodtype.trim();
    }
}