package org.goodsManagement.po;

import java.util.Date;

public class InRepositoryDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inrepository.id
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inrepository.intime
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Date intime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inrepository.goodid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Integer goodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inrepository.goodnumber
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Integer goodnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inrepository.suppliers
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private String suppliers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inrepository.linkman
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inrepository.phone
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inrepository.operatorid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Integer operatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inrepository.comments
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inrepository.id
     *
     * @return the value of inrepository.id
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inrepository.id
     *
     * @param id the value for inrepository.id
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inrepository.intime
     *
     * @return the value of inrepository.intime
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Date getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inrepository.intime
     *
     * @param intime the value for inrepository.intime
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setIntime(Date intime) {
        this.intime = intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inrepository.goodid
     *
     * @return the value of inrepository.goodid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inrepository.goodid
     *
     * @param goodid the value for inrepository.goodid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inrepository.goodnumber
     *
     * @return the value of inrepository.goodnumber
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Integer getGoodnumber() {
        return goodnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inrepository.goodnumber
     *
     * @param goodnumber the value for inrepository.goodnumber
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setGoodnumber(Integer goodnumber) {
        this.goodnumber = goodnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inrepository.suppliers
     *
     * @return the value of inrepository.suppliers
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public String getSuppliers() {
        return suppliers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inrepository.suppliers
     *
     * @param suppliers the value for inrepository.suppliers
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setSuppliers(String suppliers) {
        this.suppliers = suppliers == null ? null : suppliers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inrepository.linkman
     *
     * @return the value of inrepository.linkman
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inrepository.linkman
     *
     * @param linkman the value for inrepository.linkman
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inrepository.phone
     *
     * @return the value of inrepository.phone
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inrepository.phone
     *
     * @param phone the value for inrepository.phone
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inrepository.operatorid
     *
     * @return the value of inrepository.operatorid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Integer getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inrepository.operatorid
     *
     * @param operatorid the value for inrepository.operatorid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setOperatorid(Integer operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inrepository.comments
     *
     * @return the value of inrepository.comments
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inrepository.comments
     *
     * @param comments the value for inrepository.comments
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}