package org.goodsManagement.po;

import java.util.Date;

public class OutRepositoryDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outrepository.id
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outrepository.outtime
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Date outtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outrepository.goodid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Integer goodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outrepository.goodnumber
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Integer goodnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outrepository.operatorid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Integer operatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outrepository.deptid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outrepository.standardnumber
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Integer standardnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outrepository.comments
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outrepository.id
     *
     * @return the value of outrepository.id
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outrepository.id
     *
     * @param id the value for outrepository.id
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outrepository.outtime
     *
     * @return the value of outrepository.outtime
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Date getOuttime() {
        return outtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outrepository.outtime
     *
     * @param outtime the value for outrepository.outtime
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setOuttime(Date outtime) {
        this.outtime = outtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outrepository.goodid
     *
     * @return the value of outrepository.goodid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outrepository.goodid
     *
     * @param goodid the value for outrepository.goodid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outrepository.goodnumber
     *
     * @return the value of outrepository.goodnumber
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Integer getGoodnumber() {
        return goodnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outrepository.goodnumber
     *
     * @param goodnumber the value for outrepository.goodnumber
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setGoodnumber(Integer goodnumber) {
        this.goodnumber = goodnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outrepository.operatorid
     *
     * @return the value of outrepository.operatorid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Integer getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outrepository.operatorid
     *
     * @param operatorid the value for outrepository.operatorid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setOperatorid(Integer operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outrepository.deptid
     *
     * @return the value of outrepository.deptid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outrepository.deptid
     *
     * @param deptid the value for outrepository.deptid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outrepository.standardnumber
     *
     * @return the value of outrepository.standardnumber
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Integer getStandardnumber() {
        return standardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outrepository.standardnumber
     *
     * @param standardnumber the value for outrepository.standardnumber
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setStandardnumber(Integer standardnumber) {
        this.standardnumber = standardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outrepository.comments
     *
     * @return the value of outrepository.comments
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outrepository.comments
     *
     * @param comments the value for outrepository.comments
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
    private String outrepositoryid;

    public String getOutrepositoryid() {
        return outrepositoryid;
    }

    public void setOutrepositoryid(String outrepositoryid) {
        this.outrepositoryid = outrepositoryid;
    }
}