package org.goodsManagement.po;

import java.util.Date;

public class OutRepositoryDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outrepository.id
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outrepository.outtime
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    private Date outtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outrepository.goodid
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    private Integer goodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outrepository.operator
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    private Integer operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outrepository.deptid
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outrepository.comments
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outrepository.id
     *
     * @return the value of outrepository.id
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outrepository.id
     *
     * @param id the value for outrepository.id
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outrepository.outtime
     *
     * @return the value of outrepository.outtime
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    public Date getOuttime() {
        return outtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outrepository.outtime
     *
     * @param outtime the value for outrepository.outtime
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    public void setOuttime(Date outtime) {
        this.outtime = outtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outrepository.goodid
     *
     * @return the value of outrepository.goodid
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outrepository.goodid
     *
     * @param goodid the value for outrepository.goodid
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outrepository.operator
     *
     * @return the value of outrepository.operator
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outrepository.operator
     *
     * @param operator the value for outrepository.operator
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outrepository.deptid
     *
     * @return the value of outrepository.deptid
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outrepository.deptid
     *
     * @param deptid the value for outrepository.deptid
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outrepository.comments
     *
     * @return the value of outrepository.comments
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outrepository.comments
     *
     * @param comments the value for outrepository.comments
     *
     * @mbggenerated Sun Sep 20 14:45:05 CST 2015
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}