package org.goodsManagement.po;

public class StaffDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.id
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staffname
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private String staffname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.sex
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.deptid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    private Integer deptid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.id
     *
     * @return the value of staff.id
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.id
     *
     * @param id the value for staff.id
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staffname
     *
     * @return the value of staff.staffname
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public String getStaffname() {
        return staffname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staffname
     *
     * @param staffname the value for staff.staffname
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setStaffname(String staffname) {
        this.staffname = staffname == null ? null : staffname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.sex
     *
     * @return the value of staff.sex
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.sex
     *
     * @param sex the value for staff.sex
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.deptid
     *
     * @return the value of staff.deptid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.deptid
     *
     * @param deptid the value for staff.deptid
     *
     * @mbggenerated Sun Sep 20 19:32:38 CST 2015
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }
}