package org.goodsManagement.mapper;

import org.goodsManagement.po.DeptDto;

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table dept
 *
 * @mbggenerated Sun Sep 20 14:45:05 CST 2015
 */
public interface DeptDtoMapper extends BaseMapper<DeptDto> {
}