package org.goodsManagement.mapper;

import org.goodsManagement.po.DeptDto;

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table dept
 *
 * @mbggenerated Sun Sep 20 14:45:05 CST 2015
 */
public interface DeptDtoMapper {
    int deleteByPrimaryKey(Integer id);

    int insert(DeptDto record);

    int insertSelective(DeptDto record);

    DeptDto selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(DeptDto record);

    int updateByPrimaryKey(DeptDto record);
}