package org.goodsManagement.mapper;

import org.goodsManagement.po.GetGoodsDto;

public interface GetGoodsDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getgoods
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getgoods
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int insert(GetGoodsDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getgoods
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int insertSelective(GetGoodsDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getgoods
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    GetGoodsDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getgoods
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int updateByPrimaryKeySelective(GetGoodsDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table getgoods
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int updateByPrimaryKey(GetGoodsDto record);
}