package org.goodsManagement.mapper;

import org.goodsManagement.po.GetGoodsDto;

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table getgoods
 *
 * @mbggenerated Sun Sep 20 14:45:05 CST 2015
 */
public interface GetGoodsDtoMapper extends BaseMapper<GetGoodsDto> {
}