package org.goodsManagement.mapper;

import org.goodsManagement.po.GoodsDto;

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table goods
 *
 * @mbggenerated Sun Sep 20 14:45:05 CST 2015
 */
public interface GoodsDtoMapper {

    int deleteByPrimaryKey(Integer id);

    int insert(GoodsDto record);

    int insertSelective(GoodsDto record);

    GoodsDto selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(GoodsDto record);

    int updateByPrimaryKey(GoodsDto record);
}