package org.goodsManagement.mapper;

import org.goodsManagement.po.GoodsDto;

public interface GoodsDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int insert(GoodsDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int insertSelective(GoodsDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    GoodsDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int updateByPrimaryKeySelective(GoodsDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int updateByPrimaryKey(GoodsDto record);
}