package org.goodsManagement.mapper;

import org.goodsManagement.po.InRepositoryDto;

public interface InRepositoryDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inrepository
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inrepository
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int insert(InRepositoryDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inrepository
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int insertSelective(InRepositoryDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inrepository
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    InRepositoryDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inrepository
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int updateByPrimaryKeySelective(InRepositoryDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inrepository
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int updateByPrimaryKey(InRepositoryDto record);
}