package org.goodsManagement.mapper;

import org.goodsManagement.po.OutRepositoryDto;

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table outrepository
 *
 * @mbggenerated Sun Sep 20 14:45:05 CST 2015
 */
public interface OutRepositoryDtoMapper extends BaseMapper<OutRepositoryDto> {

}