package org.goodsManagement.mapper;

import org.goodsManagement.po.StaffDto;

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table staff
 *
 * @mbggenerated Sun Sep 20 14:45:05 CST 2015
 */
public interface StaffDtoMapper {

    int deleteByPrimaryKey(Integer id);

    int insert(StaffDto record);

    int insertSelective(StaffDto record);

    StaffDto selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(StaffDto record);

    int updateByPrimaryKey(StaffDto record);
}