package org.goodsManagement.mapper;

import org.goodsManagement.po.StaffDto;

public interface StaffDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int insert(StaffDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int insertSelective(StaffDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    StaffDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int updateByPrimaryKeySelective(StaffDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Sep 20 09:05:17 CST 2015
     */
    int updateByPrimaryKey(StaffDto record);
}