package org.goodsManagement.mapper;

import org.goodsManagement.po.UserDto;

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table user
 *
 * @mbggenerated Sun Sep 20 14:45:05 CST 2015
 */
public interface UserDtoMapper {

    int deleteByPrimaryKey(Integer id);

    int insert(UserDto record);

    int insertSelective(UserDto record);

    UserDto selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(UserDto record);

    int updateByPrimaryKey(UserDto record);
}